#encoding: utf-8
import re
import mysql.connector
import oss2
import csv
import sys
import datetime
reload(sys)
sys.setdefaultencoding('utf-8')
import requests
import os
db_host = os.environ['db_host']
db_password = os.environ['db_password']
oss_host = os.environ['oss_host']
oss_password = os.environ['oss_password']
auth = oss2.Auth(oss_host, oss_password)
bucket = oss2.Bucket(auth, 'oss-cn-shanghai.aliyuncs.com', 'cti-pub-files')


def get_github(keywords):
    db = mysql.connector.connect(user='root',
                                 password='Bumble@20180628',
                                 host='rm-j6c9v62tlv18x957p.mysql.rds.aliyuncs.com',
                                 port='3306',
                                 database='github'
                                 )
    db.set_charset_collation('utf8')
    cursor = db.cursor()
    count = len(keywords)
    keystring = 'where github_keyWords = "' + str(keywords[0]) + '"'
    if count > 1:
        for key in keywords[1:]:
            keystring = keystring + 'or github_keyWords = "' + str(key) + '"'

    sql = '''select github_keyWords, github_author, github_htmlUrl, github_path,github_score,github_tags,github_description from  github_result %s and github_tags != 'no' and github_description != 'None' order by github_score desc limit 5;''' % keystring
    print(sql)
    cursor.execute(sql)
    dates = cursor.fetchall()
    datelist = []
    for date in dates:
        dic = {}

        dic['github_author'] = date[1]
        dic['github_htmlUrl'] = date[2]
        dic['github_path'] = date[3]
        dic['github_description'] = date[6]
        datelist.append(dic)
    try:
        db.commit()
    except:
        # if unexecuted, rollback
        db.rollback()
    print(len(datelist))
    return datelist


def get_weixin(keywords):
    db = mysql.connector.connect(user='root',
                                 password='Bumble@20180628',
                                 host='rm-j6c9v62tlv18x957p.mysql.rds.aliyuncs.com',
                                 port='3306',
                                 database='0_social_media'
                                 )
    db.set_charset_collation('utf8')
    cursor = db.cursor()
    count = len(keywords)
    keystring = 'where keyword = "' + str(keywords[0]) + '"'
    if count > 1:
        for key in keywords[1:]:
            keystring = keystring + 'or keyword = "' + str(key) + '"'

    sql = '''select title, content, nickname, link,date from  wechat %s order by date desc limit 5;''' % keystring
    print(sql)
    cursor.execute(sql)
    dates = cursor.fetchall()
    datelist = []
    for date in dates:
        dic = {}

        dic['title'] = date[0]
        # print(dic['title'])
        dic['content'] = date[1]
        dic['nickname'] = date[2]
        dic['link'] = date[3]
        dic['date'] = date[4]
        datelist.append(dic)

    try:
        db.commit()
    except:
        # if unexecuted, rollback
        db.rollback()
    print(len(datelist))
    return datelist


def write_html(filename, github_keywords, weixin_keywords,report_id,request_id):
    git_kw = github_keywords[0]
    wx_kw = weixin_keywords[0]
    if len(github_keywords) > 1:
        for git in github_keywords[1:]:
            git_kw = git_kw + '、' + str(git)
    if len(weixin_keywords) > 1:
        for wx in weixin_keywords[1:]:
            wx_kw = wx_kw + '、' + str(wx)

    github = get_github(github_keywords)
    # print(github)
    weixin = get_weixin(weixin_keywords)
    with open(filename, 'w') as f:



        f.write('''﻿<html class=" js flexbox flexboxlegacy webgl no-touch geolocation rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface no-generatedcontent svg inlinesvg smil svgclippaths" lang="zh-cn" xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn" style="">\n''')
        f.write('''\n''')
        f.write('''<head>\n''')
        f.write('''    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n''')
        f.write('''    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n''')
        f.write('''    <meta name="viewport" content="width=device-width, initial-scale=1">\n''')
        days1 = datetime.date(2018, 07, 01)
        days2 = datetime.date.today()
        num = (days2-days1).days
        weeks = num//7 + 1
        f.write('''    <title>云雀数据安全威胁情报（第%s周）</title>\n''' % weeks)
        f.write('''    <meta http-equiv="Content-Language" content="en">\n''')
        f.write('''    <meta name="apple-mobile-web-app-capable" content="yes">\n''')
        f.write('''    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">\n''')
        f.write('''    <meta name="msapplication-config" content="/theme/xml/ieconfig.xml">\n''')
        f.write('''    <link rel="shortcut icon" href="https://www.ey.com/ecimages/EYlogo.ico">\n''')
        f.write('''    <link rel="apple-touch-icon" href="https://www.ey.com/ecimages/icon2x.png">\n''')
        f.write('''    <link rel="apple-touch-startup-image" href="https://www.ey.com/ecimages/startup-image.png">\n''')
        f.write('''    <style type="text/css">\n''')
        f.write('''    @charset "UTF-8";\n''')
        f.write('''    article.type-system-ey {\n''')
        f.write('''        text-align: righ;\n''')
        f.write('''        position: relative;\n''')
        f.write('''        background: #fff;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    html {\n''')
        f.write('''        font-family: sans-serif;\n''')
        f.write('''        -ms-text-size-adjust: 100%;\n''')
        f.write('''        -webkit-text-size-adjust: 100%;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    html {\n''')
        f.write('''        box-sizing: border-box;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    * {\n''')
        f.write('''        box-sizing: border-box;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    *,\n''')
        f.write('''    *::after,\n''')
        f.write('''    *::before {\n''')
        f.write('''        box-sizing: inherit;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    body {\n''')
        f.write('''        margin: 0;\n''')
        f.write('''        padding: 0;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    body {\n''')
        f.write('''        -webkit-font-feature-settings: "kern", "liga", "pnum";\n''')
        f.write('''        -ms-font-feature-settings: "kern", "liga", "pnum";\n''')
        f.write('''        font-feature-settings: "kern", "liga", "pnum";\n''')
        f.write('''        -webkit-font-smoothing: antialiased;\n''')
        f.write('''        -moz-osx-font-smoothing: grayscale;\n''')
        f.write('''        color: #333;\n''')
        f.write('''        font-family: "Helvetica Neue", "Helvetica", "Roboto", "Arial", sans-serif;\n''')
        f.write('''        font-size: 1em;\n''')
        f.write('''        line-height: 1.4;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    body {\n''')
        f.write('''        margin: 0;\n''')
        f.write('''        height: 100%;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    article,\n''')
        f.write('''    aside,\n''')
        f.write('''    details,\n''')
        f.write('''    figcaption,\n''')
        f.write('''    figure,\n''')
        f.write('''    footer,\n''')
        f.write('''    header,\n''')
        f.write('''    hgroup,\n''')
        f.write('''    main,\n''')
        f.write('''    menu,\n''')
        f.write('''    nav,\n''')
        f.write('''    section,\n''')
        f.write('''    summary {\n''')
        f.write('''        display: block;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .article>section[class*=section]:nth-child(odd) {\n''')
        f.write('''        background-color: #f0f0f0;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .article>section.section0 {\n''')
        f.write('''        padding-top: 60px;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    @media (min-width: 1200px) {\n''')
        f.write('''        .sl-landing>section,\n''')
        f.write('''        article>section,\n''')
        f.write('''        body>section {\n''')
        f.write('''            padding-left: 0;\n''')
        f.write('''            padding-right: 0;\n''')
        f.write('''        }\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    @media (min-width: 1200px) {\n''')
        f.write('''        .sl-landing>section,\n''')
        f.write('''        article>section,\n''')
        f.write('''        body>section {\n''')
        f.write('''            padding-left: 0;\n''')
        f.write('''            padding-right: 0;\n''')
        f.write('''        }\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    @media (min-width: 940px) {\n''')
        f.write('''        .sl-landing>section,\n''')
        f.write('''        article>section,\n''')
        f.write('''        body>section {\n''')
        f.write('''            padding: 40px;\n''')
        f.write('''        }\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    @media (min-width: 768px) {\n''')
        f.write('''        .sl-landing>section,\n''')
        f.write('''        article>section,\n''')
        f.write('''        body>section {\n''')
        f.write('''            padding: 40px 20px;\n''')
        f.write('''        }\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .sl-landing>section,\n''')
        f.write('''    article>section,\n''')
        f.write('''    body>section {\n''')
        f.write('''        position: relative;\n''')
        f.write('''        -webkit-transition: all 0.4s;\n''')
        f.write('''        transition: all 0.4s;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    @media (min-width: 940px) {\n''')
        f.write('''        .container::after {\n''')
        f.write('''            clear: both;\n''')
        f.write('''            content: "";\n''')
        f.write('''            display: block;\n''')
        f.write('''        }\n''')
        f.write('''        .sl-landing .container {\n''')
        f.write('''            max-width: 68em;\n''')
        f.write('''        }\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .container::after {\n''')
        f.write('''        clear: both;\n''')
        f.write('''        content: "";\n''')
        f.write('''        display: block;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .maincolumn:last-child {\n''')
        f.write('''        margin-right: 0;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    @media (min-width: 768px) {\n''')
        f.write('''        .maincolumn {\n''')
        f.write('''            padding: 0;\n''')
        f.write('''            float: left;\n''')
        f.write('''            display: block;\n''')
        f.write('''            margin-right: 2.3576515979%;\n''')
        f.write('''            width: 100%;\n''')
        f.write('''            margin-right: 0;\n''')
        f.write('''        }\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    @media only screen and (min-width: 737px) {\n''')
        f.write('''        .type-system-ey .maincolumn table,\n''')
        f.write('''        .type-system-ey section h2 {\n''')
        f.write('''            margin: 1em 0;\n''')
        f.write('''        }\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .type-system-ey .maincolumn h2,\n''')
        f.write('''    .type-system-ey section h2 {\n''')
        f.write('''        font-size: 2.4em;\n''')
        f.write('''        margin: 0 0 0.5em;\n''')
        f.write('''        font-weight: normal;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    @media screen and (min-width: 40em) {\n''')
        f.write('''        .maincolumn h2,\n''')
        f.write('''        section h2 {\n''')
        f.write('''            width: 80%;\n''')
        f.write('''            letter-spacing: -0.03em;\n''')
        f.write('''            line-height: 1.1;\n''')
        f.write('''            padding: 0;\n''')
        f.write('''            margin: 1em 0;\n''')
        f.write('''        }\n''')
        f.write('''        .type-system-ey .maincolumn h2,\n''')
        f.write('''        .type-system-ey section h2 {\n''')
        f.write('''            font-size: 2.4em;\n''')
        f.write('''            margin: 0 0 0.5em;\n''')
        f.write('''            font-weight: normal;\n''')
        f.write('''        }\n''')
        f.write('''        .sl-landing .maincolumn h2,\n''')
        f.write('''        .sl-landing section h2 {\n''')
        f.write('''            font-size: 2.8em;\n''')
        f.write('''            padding-top: 40px;\n''')
        f.write('''            margin-top: 0;\n''')
        f.write('''        }\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .maincolumn h2,\n''')
        f.write('''    section h2 {\n''')
        f.write('''        font-family: "Interstate-bold", sans-serif;\n''')
        f.write('''        font-size: 1.6em;\n''')
        f.write('''        font-weight: 400;\n''')
        f.write('''        line-height: 1.1em;\n''')
        f.write('''        margin-bottom: 0.5em;\n''')
        f.write('''        letter-spacing: -.03em;\n''')
        f.write('''        color: #646464;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    h1,\n''')
        f.write('''    h2,\n''')
        f.write('''    h3,\n''')
        f.write('''    p {\n''')
        f.write('''        margin: 0;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    h1,\n''')
        f.write('''    h2,\n''')
        f.write('''    h3,\n''')
        f.write('''    h4,\n''')
        f.write('''    h5,\n''')
        f.write('''    h6 {\n''')
        f.write('''        font-family: "Helvetica Neue", "Helvetica", "Roboto", "Arial", sans-serif;\n''')
        f.write('''\n''')
        f.write('''        line-height: 1.2;\n''')
        f.write('''        margin: 0 0 0.7em;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    p {\n''')
        f.write('''        -webkit-font-feature-settings: "onum" 1, "pnum" 1;\n''')
        f.write('''        font-feature-settings: "onum" 1, "pnum" 1;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    p {\n''')
        f.write('''        font-family: "Helvetica", sans-serif;\n''')
        f.write('''        font-weight: 300;\n''')
        f.write('''        margin: 1em 0;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    p {\n''')
        f.write('''        color: #333;\n''')
        f.write('''        line-height: 1.4;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    p {\n''')
        f.write('''        margin: 0 0 0.7em;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    h3 {\n''')
        f.write('''        font-family: "Interstate-bold", sans-serif;\n''')
        f.write('''        font-size: 1.3em;\n''')
        f.write('''        color: #646464;\n''')
        f.write('''        font-weight: 700;\n''')
        f.write('''        line-height: 1.4em;\n''')
        f.write('''        margin-top: 0.5em;\n''')
        f.write('''        margin-bottom: 0.5em;\n''')
        f.write('''        letter-spacing: -.02em;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    table.dataframe {\n''')
        f.write('''        font-size: 1em;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    table {\n''')
        f.write('''        -webkit-font-feature-settings: "kern", "liga", "tnum";\n''')
        f.write('''        -ms-font-feature-settings: "kern", "liga", "tnum";\n''')
        f.write('''        font-feature-settings: "kern", "liga", "tnum";\n''')
        f.write('''        border-collapse: collapse;\n''')
        f.write('''        margin: 0.7em 0;\n''')
        f.write('''        table-layout: fixed;\n''')
        f.write('''        width: 100%;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    table {\n''')
        f.write('''        border-collapse: collapse;\n''')
        f.write('''        border-spacing: 0;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    tr,\n''')
        f.write('''    td,\n''')
        f.write('''    th {\n''')
        f.write('''        vertical-align: middle;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .dataframe th {\n''')
        f.write('''        background: #fff000;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    #thc1 {\n''')
        f.write('''        width: 18%;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    #thc2 {\n''')
        f.write('''        width: 20%;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    #thc3 {\n''')
        f.write('''        width: 12%;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    #thc4 {\n''')
        f.write('''        width: 50%;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    td,\n''')
        f.write('''    th {\n''')
        f.write('''        padding: 0;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''\n''')
        f.write('''    th {\n''')
        f.write('''        border-bottom: 1px solid #a6a6a6;\n''')
        f.write('''        font-weight: 600;\n''')
        f.write('''        padding: 0.7em 0;\n''')
        f.write('''        text-align: left;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    td {\n''')
        f.write('''        border-bottom: 1px solid #ccc;\n''')
        f.write('''        padding: 0.7em 0;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    a {\n''')
        f.write('''        color: #369;\n''')
        f.write('''        text-decoration: none;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    article a {\n''')
        f.write('''        font-weight: bold;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    a {\n''')
        f.write('''        color: #369;\n''')
        f.write('''        text-decoration: none;\n''')
        f.write('''        -webkit-transition: color 0.1s linear;\n''')
        f.write('''        transition: color 0.1s linear;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    a {\n''')
        f.write('''        background-color: transparent;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .container {\n''')
        f.write('''        max-width: 52em;\n''')
        f.write('''        margin-left: auto;\n''')
        f.write('''        margin-right: auto;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    a {\n''')
        f.write('''        color: #369;\n''')
        f.write('''        text-decoration: none;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    article a {\n''')
        f.write('''        font-weight: bold;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    a.logo {\n''')
        f.write('''        height: 70px;\n''')
        f.write('''        width: 145px;\n''')
        f.write('''        margin: 10px 0;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    a.logo {\n''')
        f.write('''        float: right;\n''')
        f.write('''        width: 145px;\n''')
        f.write('''        height: 66px;\n''')
        f.write('''        margin: -20px -61px -100px;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    a.logo img {\n''')
        f.write('''        height: 100%;\n''')
        f.write('''        max-height: 70px;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    h4 {\n''')
        f.write('''        font-size: 0.8em;\n''')
        f.write('''        color: #646464;\n''')
        f.write('''        font-weight: 700;\n''')
        f.write('''        line-height: 1.2em;\n''')
        f.write('''        margin-top: 0.5em;\n''')
        f.write('''        margin-bottom: 0.5em;\n''')
        f.write('''        letter-spacing: -.02em;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .footer p {\n''')
        f.write('''        color: rgba(255, 255, 255, 0.6);\n''')
        f.write('''        font-size: 0.8em;\n''')
        f.write('''        line-height: 1.5em;\n''')
        f.write('''        margin: 1em auto;\n''')
        f.write('''        max-width: 52em;\n''')
        f.write('''    }\n''')
        f.write('''\n''')
        f.write('''    .footer {\n''')
        f.write('''        padding: 10px;\n''')
        f.write('''        background: #333;\n''')
        f.write('''        width: 100%;\n''')
        f.write('''    }\n''')
        f.write('''    .topdetails {\n''')
        f.write('''    	font-size:0.8em;\n''')
        f.write('''    	color: #646464;\n''')
        f.write('''    	text-align:center;\n''')
        f.write('''    }\n''')
        f.write('''    </style>\n''')
        f.write('''    </div>\n''')
        f.write('''    </div>\n''')
        f.write('''    </div>\n''')
        f.write('''</head>\n''')
        f.write('''    <article class="article type-system-ey ">\n''')
        f.write('''<p class="topdetails">若该邮件无法正常显示，请<a href="https://cti-pub-files.oss-cn-shanghai.aliyuncs.com/%s/datesecurity.html" target="_blank">点击此处查看详情</a></p>\n'''%report_id)
        f.write('''        <section class="section0" id="section0" data-section-title="漏洞级别概况及目录" style="background-color:#F0F0F0">\n''')
        f.write('''            <div class="container">\n''')
        f.write('''                <div class="eyscrollogo"><a href="#" class="logo">\n''')
        f.write('''</a></div>\n''')
        f.write('''                <div class="maincolumn">\n''')
        days1 = datetime.date(2018, 07, 01)
        days2 = datetime.date.today()
        num = (days2-days1).days
        weeks = num//7 + 1
        f.write('''                    <h2>云雀数据安全威胁情报（第%s周）</h2>\n''' % weeks)
        f.write('''                         <section class="section3" id="section3" data-section-title="金融事件" style="background-color:#F0F0F0">\n''')
        f.write('''                        <div class="container">\n''')
        f.write('''                            <div class="maincolumn">\n''')
        f.write('''                                <h3>社交网络</h3> </div>\n''')
        f.write('''                                 <p>我们根据%s关键词在微博和微信等社交网络上进行检索，检索结果如下：</p>\n'''% wx_kw)
        f.write('''                        </div>\n''')
        f.write('''\n''')

        for index, wx in enumerate(weixin):
            link ='http://weixin.sogou.com/weixin?type=2&query=' +wx['title'] + '&ie=utf8&s_from=input&_sug_=y&_sug_type_='
            f.write('''                    <p><a href="%s" target="_blank">%d.%s</a></p>\n''' % (link,index + 1,wx['title']))
            #print(wx['content'][:200])
            f.write('''                                <p>公众号名称：%s</p>\n''' % wx['nickname'])
            f.write('''                                <p>时间：%s</p>\n''' % wx['date'])
            f.write('''                                <p>摘要：%s...</p>\n''' % wx['content'][:200])




        f.write('''                        <!-- <div class="col large-3">  </div> -->\n''')
        f.write('''                        <section class="section4" id="section4" data-section-title="科技事件" style="background-color:#F0F0F0">\n''')
        f.write('''                            <div class="container">\n''')
        f.write('''                                <div class="maincolumn">\n''')
        f.write('''                                    <h3>开源社区</h3> </div>\n''')
        f.write('''                <p>我们根据%s关键词在github开源社区上进行检索，检索结果如下：</p></div>\n''' %git_kw)





        f.write('''                            </div>\n''')

        for index, gith in enumerate(github):
            print('here')
            f.write('''                    <p><a href="%s" target="_blank">%d.%s</a></p>\n''' % (gith['github_htmlUrl'], index + 1, gith['github_path']))
            f.write('''                                <p>作者：%s</p>\n''' % gith['github_author'])
            f.write('''                                <p>摘要：%s...</p>\n''' % gith['github_description'])




        f.write('''                            <!-- <div class="col large-3">  </div> -->\n''')
        f.write('''                            <section class="section5" id="section5" data-section-title="零售事件" style="background-color:#F0F0F0">\n''')
        f.write('''                                <div class="container">\n''')
        f.write('''                                    <div class="maincolumn">\n''')
        f.write('''                                        <h3>搜索引擎</h3> </div>\n''')
        f.write('''                                       <p>我们根据*************关键词在google等搜索引擎上进行检索，检索结果如下：</p>\n''')
        f.write('''                                </div>\n''')
        f.write('''<p><a href="https://blog.trendmicro.com/trendlabs-security-intelligence/drupal-vulnerability-cve-2018-7602-exploited-to-deliver-monero-mining-malware/" target="_blank">1.Drupal Vulnerability (CVE-2018-7602) Exploited to Deliver Monero-Mining Malware</a></p>\n''')
        f.write('''\n''')
        f.write('''<p>摘要：We were able to observe a series of network attacks exploiting CVE-2018-7602, a security flaw in the Drupal content management framework. For now, these attacks aim to turn affected systems into... </p>\n''')
        f.write('''<p><a href="https://blog.trendmicro.com/trendlabs-security-intelligence/another-potential-muddywater-campaign-uses-powershell-based-prb-backdoor/" target="_blank">2.Another Potential MuddyWater Campaign uses Powershell-based PRB-Backdoor</a></p>\n''')
        f.write('''\n''')
        f.write('''<p>摘要：we found a new sample that may be related to the MuddyWater campaign. Like the previous campaigns, these samples again involve a Microsoft Word document embedded with a malicious macro ...</p>\n''')
        f.write('''<p><a href="https://blog.trendmicro.com/trendlabs-security-intelligence/confucius-update-new-tools-and-techniques-further-connections-with-patchwork/" target="_blank">3.Confucius Update: New Tools and Techniques, Further Connections with Patchwork</a></p>\n''')
        f.write('''\n''')
        f.write('''<p>摘要：We look into the latest tools and techniques used by Confucius, as the threat actor seems to have a new modus operandi, setting up two new websites and new payloads with which to compromise its targets...</p>\n''')
        f.write('''<p><a href="https://blog.trendmicro.com/trendlabs-security-intelligence/another-potential-muddywater-campaign-uses-powershell-based-prb-backdoor/" target="_blank">4.Another Potential MuddyWater Campaign uses Powershell-based PRB-Backdoor</a></p>\n''')
        f.write('''\n''')
        f.write('''<p>摘要：we found a new sample that may be related to the MuddyWater campaign. Like the previous campaigns, these samples again involve a Microsoft Word document embedded with a malicious macro that is ...</p>\n''')
        f.write('''<p><a href="https://blog.trendmicro.com/trendlabs-security-intelligence/confucius-update-new-tools-and-techniques-further-connections-with-patchwork/" target="_blank">5.Confucius Update: New Tools and Techniques, Further Connections with Patchwork</a></p>\n''')
        f.write('''\n''')
        f.write('''<p>摘要：We look into the latest tools and techniques used by Confucius, as the threat actor seems to have a new modus operandi, setting up two new websites and new payloads with which to compromise its targets...</p>\n''')
        f.write('''                </div>\n''')
        f.write('''                    <div class="container">\n''')
        f.write('''                        <div class="maincolumn">\n''')
        f.write('''                        <h4>更多详细内容请<a href="https://cti-pub-files.oss-cn-shanghai.aliyuncs.com/%s/datesecurity" target="_blank">点击此处查看</a></h4></div>\n'''%report_id)
        f.write('''                    </div>\n''')
        f.write('''                </div>\n''')
        f.write('''    </article>\n''')
        f.write('''    <footer class="footer" id="footer" role="contentinfo">\n''')
        f.write('''        <div class="footer-logo">\n''')
        f.write('''            <div class="footer-links"></div>\n''')
        f.write('''            <p class="detail">声明：以上内容均来自互联网，由CTI网络威胁情报团队整理，其版权归属原作者所有，其观点并不代表我方观点和意见，请酌情参考或采用。若对以上所引用内容有任何疑问或问题，请与services@eycyber.com联系。</p>\n''')
        f.write('''        </div>\n''')
        f.write('''    </footer>\n''')
        f.write('''    </body>\n''')
        f.write('''\n''')
        f.write('''</html>\n''')
    with open('datesecurity_mail', 'rb') as fileobj:
        directory = report_id + '/datesecurity_mail'
        result = bucket.put_object(directory,fileobj)
def main():
    write_html('datesecurity_mail.html', ['Lancome','Armani'], ['GDPR','云安全'],'测试机','测试机')


if __name__ == '__main__':
    main()